platform :ios, '10.2'

target 'Clima' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clima

    pod 'SwiftyJSON', '~> 4.2'
    pod 'Alamofire'
    pod 'SVProgressHUD'

end
